# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "castlegimbal"
BBFILE_PATTERN_castlegimbal = "^${LAYERDIR}/"
BBFILE_PRIORITY_castlegimbal = "6"

LAYERDEPENDS_meta-castle-gimbal = "core raspberry openembbed-layer meta-python"
LAYERSERIES_COMPAT_meta-castle-gimbal = "scarthgap"
