require conf/distro/poky.conf

DISTRO = "castle-gimbal"
DISTRO_NAME = "Castle Gimbal"
DISTRO_VERSION = "1.0"

INIT_MANAGER = "systemd"

DISTRO_FEATURES:append = " systemd wifi blutooth"
DISTRO_FEATURES:remove = " sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
